### ISSUE TITLE
New to github dont know how to work

### ISSUE THREAD

**Issue by Sausagemuncher2** [LacledesLAN/gamesvr-tf2#3]
Hey im new to github and I have no idea how this works. If you could teach me how to use the application without linux it would be really helpful.

**Comment by dudleycodes** [comment]
@Sausagemuncher2 welcome to Github!

This project will always be linux-based. If you're looking to run a TF2 server on windows, I recommend you google for some guides for "TF2 dedicated server windows".  This one seems pretty good: https://wiki.teamfortress.com/wiki/Windows_dedicated_server

If a guide doesn't make sense, just keep trying others - or googling the things mentioned in the guide, and eventually you'll get there!

If you're wanting to learn how to use Github itself, I recommend searching for tutorials on Youtube. You can use Github from any type of computer (Windows, Mac, Linux, phones, etc).

Best of luck!
